services:
  website:
    container_name: website
    image: ghcr.io/zehro/website-docker:latest
    networks:
      - proxy-net
    restart: unless-stopped

networks:
  proxy-net:
    external: true